import json
import sys
if sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')
import numpy as np
from src.providers.embedding_provider import embed_text

# --- 1. Define Reference Sets ---
REF_SIMPLE = [
    "Who are the primary NITI Aayog authors credited with writing the National Strategy for Artificial Intelligence report?",
    "What BLEU score did the Transformer big model achieve on the WMT 2014 English-to-German translation task?",
    "What exact mathematical formula defines Scaled Dot-Product Attention in the Transformer paper?",
    "How many Assistant Professors are at GHMC, Bangalore?",
    "What was the title of Bill No. 64 of 2009?",
    "In which session was the Right of Children to Free and Compulsory Education Bill passed?",
    "Which ministry passed the Finance (No.2) Bill, 2009?",
    "How many parallel attention heads h are employed in the Multi-Head Attention mechanism of the base Transformer model?",
    "What item section covers the Financial Statements in Part I of the Form 10-Q report?"
]

REF_SYNTHESIS = [
    "What is the relationship between AI intervention in agriculture and maintaining overall GDP growth in India?",
    "What is the statutory relationship between the National Financial Reporting Authority (NFRA) and Section 132 of the Companies Act 2013?",
    "Why is the dot product scaled by 1/sqrt(d_k) in Scaled Dot-Product Attention as key dimension d_k grows large?",
    "How do expense ratio differences between Direct Plans and Regular Plans impact long-term net returns?",
    "Compare Debt Mutual Funds versus Bank Fixed Deposits regarding liquidity, flexibility, and penalty structures.",
    "What are the three architectural USPs of CodeCouncil?",
    "Why was Supabase not integrated into CodeCouncil?",
    "What is the MVP focus scheme for WB Digital Sahayak?",
    "What is the main difference between Linear Attention and standard Attention?",
    "What relationship exists between inflation rates and real returns generated by fixed income assets in India?"
]

print("Computing reference centroids...")
emb_simple = np.array([embed_text(q) for q in REF_SIMPLE])
centroid_simple = np.mean(emb_simple, axis=0)
centroid_simple /= np.linalg.norm(centroid_simple)

emb_synthesis = np.array([embed_text(q) for q in REF_SYNTHESIS])
centroid_synthesis = np.mean(emb_synthesis, axis=0)
centroid_synthesis /= np.linalg.norm(centroid_synthesis)

# --- 2. Load Evaluation Queries ---
with open('d:/WORK/knowledge-retrieval-engine/backend/llm_ground_truths.json', 'r', encoding='utf-8') as f:
    u_queries = json.load(f)
with open('d:/WORK/knowledge-retrieval-engine/backend/tests/data/advance/eval_60_queries.json', 'r', encoding='utf-8') as f:
    x_queries = json.load(f)

all_queries = u_queries + x_queries

# Manual ground truth definition for confusion matrix
def is_truly_simple(q_text, source_file=None):
    # CSV queries are almost all simple tabular lookups
    if source_file and source_file.endswith(".csv"):
        return True
    
    # Keyword heuristics to roughly define the "ground truth" intent of the test dataset
    lower_q = q_text.lower()
    if any(x in lower_q for x in ["why", "how do", "compare", "difference", "relationship", "impact", "usp"]):
        return False
    if "how many" in lower_q or "what was" in lower_q or "who " in lower_q or "which " in lower_q:
        return True
        
    # By default, if it doesn't clearly look like synthesis, treat as simple
    # But some complex PDF/DOCX ones are synthesis
    if source_file in ["Workflow Documentation.docx", "submission.pptx"]:
        # Most of these test complex extraction/synthesis
        if "frontend framework" in lower_q or "deployment platform" in lower_q or "cost per citizen" in lower_q:
            return True # Factual lookup
        return False
    return True

# --- 3. Evaluate Classifier ---
confusion = {"true_fast_pred_fast": 0, "true_fast_pred_full": 0, "true_full_pred_full": 0, "true_full_pred_fast": 0}

print("\nRunning Classifier against 77 queries...")
for q in all_queries:
    text = q["query"]
    source = q.get("source_file")
    
    # Ground truth intent
    true_simple = is_truly_simple(text, source)
    
    # Classifier decision
    q_emb = embed_text(text)
    sim_simple = np.dot(q_emb, centroid_simple)
    sim_synth = np.dot(q_emb, centroid_synthesis)
    
    pred_simple = sim_simple > sim_synth
    
    if true_simple and pred_simple:
        confusion["true_fast_pred_fast"] += 1
    elif true_simple and not pred_simple:
        confusion["true_fast_pred_full"] += 1
        print(f"[FALSE NEGATIVE / Over-routing to Full] {text} (Source: {source})")
    elif not true_simple and not pred_simple:
        confusion["true_full_pred_full"] += 1
    else:
        confusion["true_full_pred_fast"] += 1
        print(f"[FALSE POSITIVE / Over-routing to Fast] {text} (Source: {source})")

print("\n--- Confusion Matrix ---")
print(f"Correctly Fast-Pathed: {confusion['true_fast_pred_fast']}")
print(f"Correctly Full-Pathed: {confusion['true_full_pred_full']}")
print(f"Misrouted to Fast (False Positives - Hurt Recall): {confusion['true_full_pred_fast']}")
print(f"Misrouted to Full (False Negatives - Hurt Cost): {confusion['true_fast_pred_full']}")

total = sum(confusion.values())
accuracy = (confusion["true_fast_pred_fast"] + confusion["true_full_pred_full"]) / total
print(f"Overall Accuracy: {accuracy:.2f}")
