"""Presigned URL generation for S3-hosted chunk images.

Security policy: images are NEVER exposed via public bucket ACLs or
world-readable bucket policies.  Every URL is a time-limited presigned
GET generated by the service's IAM identity at query time.

Tunable constant:
    DEFAULT_PRESIGN_EXPIRY_SECONDS — change here to affect the whole service.
"""

from kre.shared.config import get_boto3_client

# ---------------------------------------------------------------------------
# Tunable constant — adjust here without hunting call-sites.
# Default: 1 hour.  Must be <= 7 days (604 800 s) for IAM-role credentials.
# ---------------------------------------------------------------------------
DEFAULT_PRESIGN_EXPIRY_SECONDS: int = 3600


def get_signed_image_url(
    s3_key: str,
    bucket: str,
    expires_in: int = DEFAULT_PRESIGN_EXPIRY_SECONDS,
) -> str:
    """Return a presigned HTTPS GET URL for an S3 object.

    Uses the shared boto3 client factory so the endpoint URL and credentials
    (profile in dev, instance-role in prod) are sourced from config.py — no
    new boto3.client() calls are introduced here.

    Args:
        s3_key:     S3 object key (e.g. ``"extractions/doc-123/page-1.png"``).
        bucket:     S3 bucket name that holds the object.
        expires_in: Seconds until the URL expires.  Defaults to
                    ``DEFAULT_PRESIGN_EXPIRY_SECONDS`` (3 600 s).

    Returns:
        A presigned URL string valid for *expires_in* seconds.

    Raises:
        botocore.exceptions.ClientError: propagated if the presign call itself
            fails (e.g. credential issue, unknown bucket).
    """
    s3_client = get_boto3_client("s3")
    url: str = s3_client.generate_presigned_url(
        "get_object",
        Params={"Bucket": bucket, "Key": s3_key},
        ExpiresIn=expires_in,
    )
    return url
